version: "2"

run:
  timeout: 10m
  tests: true

linters:
  default: standard
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - revive
    - whitespace
    - err113
    - errorlint
    - nilerr
    - gocritic
    - nakedret
    - unconvert
    - dogsled
    - copyloopvar
    - prealloc
    - gosec
    - exhaustive
    - noctx
    - nolintlint
    - promlinter
  exclusions:
    generated: strict
    rules:
      - path: _test\.go
        linters:
          - gosec
          - noctx
          - revive

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  show-stats: true