version: "2"

linters:
  enable:
    - copyloopvar
    - dogsled
    - err113
    - errorlint
    - exhaustive
    - gocritic
    - goprintffuncname
    - gosec
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - promlinter
    - revive
    - unconvert
    - whitespace

  settings:
    revive:
      rules:
        - name: unused-parameter
          disabled: true

  exclusions:
    paths:
      - third_party
      - examples
      - builtin
    
    rules:
      - path: _test\.go
        linters:
          - funlen
          - gochecknoglobals
          - gosec
          - noctx
          - revive

issues:
  max-issues-per-linter: 0
  max-same-issues: 0