version: "2"

linters:
  enable:
    - copyloopvar
    - dogsled
    - err113
    - errorlint
    - exhaustive
    - gocritic
    - goprintffuncname
    - gosec
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - promlinter
    - revive
    - unconvert
    - whitespace

linters-settings:
  revive:
    rules:
      - name: unused-parameter
        disabled: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - gochecknoglobals
        - gosec
        - noctx
        - revive

  exclude-dirs:
    - third_party
    - examples
    - builtin